<?php

/**
 * SpareFoot Arena
 * This is the API for the SpareFoot Arena hackathon project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: patrick@sparefoot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class RatingsApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation getRatings
     *
     * Get ratings for a given user, game, or combination and rating type.
     *
     *
     * @return Http response
     */
    public function getRatings()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $type = $input['type'];

        $competitor_id = $input['competitor_id'];

        $game_id = $input['game_id'];


        return response('How about implementing getRatings as a get method ?');
    }
}
